In [31]:
import os
import pandas as pd

current_directory = os.getcwd()
print("Directorio actual:", current_directory)

Directorio actual: /Users/davidfernandez/Desktop/Projects/Dashboard-Project/Notebooks

In [30]:
PIB = pd.read_csv('/Users/davidfernandez/Desktop/PIB/1.csv', sep=';')

In [32]:
PIB

,country_code,region_name,sub_region_name,intermediate_region,country_name,income_group,year,total_gdp,total_gdp_million,gdp_variation
0,ABW,Americas,Latin America and the Caribbean,Caribbean,Aruba,Ingreso alto,1960,0.000000e+00,0.000000,0.000000
1,ABW,Americas,Latin America and the Caribbean,Caribbean,Aruba,Ingreso alto,1961,0.000000e+00,0.000000,0.000000
2,ABW,Americas,Latin America and the Caribbean,Caribbean,Aruba,Ingreso alto,1962,0.000000e+00,0.000000,0.000000
3,ABW,Americas,Latin America and the Caribbean,Caribbean,Aruba,Ingreso alto,1963,0.000000e+00,0.000000,0.000000
4,ABW,Americas,Latin America and the Caribbean,Caribbean,Aruba,Ingreso alto,1964,0.000000e+00,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
13325,ZWE,Africa,Sub-Saharan Africa,Eastern Africa,Zimbabwe,Países de ingreso mediano bajo,2017,1.758489e+10,17584.890937,4.080264
13326,ZWE,Africa,Sub-Saharan Africa,Eastern Africa,Zimbabwe,Países de ingreso mediano bajo,2018,3.415607e+10,34156.069918,5.009867
13327,ZWE,Africa,Sub-Saharan Africa,Eastern Africa,Zimbabwe,Países de ingreso mediano bajo,2019,2.183223e+10,21832.234926,-6.332446
13328,ZWE,Africa,Sub-Saharan Africa,Eastern Africa,Zimbabwe,Países de ingreso mediano bajo,2020,2.150970e+10,21509.698406,-7.816951
13329,ZWE,Africa,Sub-Saharan Africa,Eastern Africa,Zimbabwe,Países de ingreso mediano bajo,2021,2.837124e+10,28371.238666,8.468017